AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OrgId:
    Type: String
  PrimaryKeyArn:
    Type: String
Resources:
  KMSKeyReplica:
    Type: AWS::KMS::ReplicaKey
    Properties:
      Description: KMS Key for Organization RDS Backup Vaults
      Enabled: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow organization to use key
            Effect: Allow
            Principal: '*'
            Action:
              - kms:DescribeKey
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
              - kms:RetireGrant
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
          - Sid: Allow organization to set resource grants
            Effect: Allow
            Principal: '*'
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
              Bool:
                kms:GrantIsForAWSResource: true
      PendingWindowInDays: 7
      PrimaryKeyArn: !Ref PrimaryKeyArn
      Tags: 
        - Key: project
          Value: backup
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/backup-cmk
      TargetKeyId: !Ref KMSKeyReplica
  Vault:
    Type: AWS::Backup::BackupVault
    Properties:
      AccessPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable backup vault access
            Effect: Allow
            Principal: '*'
            Action:
              - backup:CopyFromBackupVault
              - backup:CopyIntoBackupVault
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
      BackupVaultName: !Sub central-backup-vault
      BackupVaultTags:
        project: backup
      EncryptionKeyArn: !GetAtt KMSKeyReplica.Arn
Outputs:
  KMSArn:
    Value: !GetAtt KMSKeyReplica.Arn
  OrganizationId:
    Value: !Ref OrgId