AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OrgId:
    Type: String
Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      MultiRegion: true
      EnableKeyRotation: true
      PendingWindowInDays: 7
      Description: KMS Key for Organization RDS Backup Vaults
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow organization to use key
            Effect: Allow
            Principal: '*'
            Action:
              - kms:DescribeKey
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
              - kms:RetireGrant
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
          - Sid: Allow organization to set resource grants
            Effect: Allow
            Principal: '*'
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
              Bool:
                kms:GrantIsForAWSResource: true
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/backup-cmk
      TargetKeyId: !Ref KMSKey
  Vault:
    Type: AWS::Backup::BackupVault
    Properties:
      AccessPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable backup vault access
            Effect: Allow
            Principal: '*'
            Action:
              - backup:CopyFromBackupVault
              - backup:CopyIntoBackupVault
            Resource: '*'
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref OrgId
      BackupVaultName: central-backup-vault
      BackupVaultTags:
        project: backup
      EncryptionKeyArn: !GetAtt KMSKey.Arn
Outputs:
  KMSArn:
    Value: !GetAtt KMSKey.Arn
  OrganizationId:
    Value: !Ref OrgId